name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # كل يوم في منتصف الليل
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: radwaadel17
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
